import '../assets/styles/globals.css';
import '../components/assets/css/bootstrap.css';
import '../components/assets/css/bootstrap-theme.css';
import '../components/assets/css/bootstrap.css';
import '../components/assets/css/bootstrap-datepicker.css';
import '../components/assets/css/bootstrap-slider.css';
import '../components/assets/css/iconmoon.css';
import '../components/assets/css/animate.css';
import '../components/assets/css/chosen.css';
import '../components/assets/css/swiper.css';
import '../components/assets/css/woocommerce.css';
import '../components/assets/css/prettyPhoto.css';
import '../components/assets/css/cs-foodbakery-plugin.css';
import '../components/assets/css/color.css';
import '../components/assets/css/widget.css';
import '../components/assets/css/responsive.css';
import '../components/assets/css/rtl.css';
import '../components/style.css';
import 'antd/dist/antd.css';
import type { AppProps } from 'next/app';
import React, { useEffect } from 'react';
import Head from 'next/head';
import { ApolloProvider, useMutation } from '@apollo/client';
import client from '../providers/client';
import AuthProvider from '../contexts/auth.context';
import { I18nextProvider } from 'react-i18next';
import i18next from 'i18next';
import { LANG_RESOURCES } from '../constants/constantLang';
import { isEmpty } from 'lodash';
import { getPayload } from '../contexts/auth.context';
function MyApp({ Component, pageProps }: AppProps) {
  const payload = getPayload();

  i18next.init({
    interpolation: { escapeValue: false }, // React already does escaping
  });

  const initialLanguage = () => {
    if (isEmpty(payload?.languages) || payload?.languages[0] === '' || !payload?.languages[0]) {
      return 'mn';
    } else {
      return payload?.languages[0];
    }
  };

  i18next.init({
    interpolation: { escapeValue: false }, // React already does escaping
    lng: initialLanguage(), // language to use
    resources: LANG_RESOURCES,
  });

  return (
    <React.Fragment>
      <Head>
        <title>Q-Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
        <link rel="icon" href="/logo.png" />
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-JXL5W43FVQ"></script>

        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <ApolloProvider client={client as any}>
        <I18nextProvider i18n={i18next}>
          <AuthProvider>
            <Component {...pageProps} />
          </AuthProvider>
        </I18nextProvider>
      </ApolloProvider>
    </React.Fragment>
  );
}

export default MyApp;
